							<?php require('core/lenguaje/'. LENGUAJE .'/'. LENGUAJE .'.ax-noticias.php'); ?>
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
											<i class="fa fa-file-text-o"></i>
											<?= TITULO_AXNOTICIAS ?>
										</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<a href="ax-noticias/articulos" class="botones"><i class="fa fa-file-text-o" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_ARTICULOS ?></span></a>
									<a href="ax-noticias/categorias" class="botones"><i class="fa fa-bookmark" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_CATEGORIAS ?></span></a>
									<a href="ax-noticias/fuentes" class="botones"><i class="fa fa-plug" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_FUENTES ?></span></a>
									<a href="ax-noticias/autores" class="botones"><i class="fa fa-user-plus" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_AUTOR ?></span></a>
									<a href="ax-noticias/tags" class="botones"><i class="fa fa-tags" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_ETIQUETAS ?></span></a>
									<a href="ax-noticias/tapas" class="botones"><i class="fa fa-newspaper-o" aria-hidden="true"></i><span class="txt-botones"><?= TITULO_AXNOTICIAS_TAPAS ?></span></a>
								</div>
							</div>
