		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<link rel="stylesheet" href="<?php echo PATH_TEMPLATE ?>/css/tablas.css">

		<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/rowreorder/1.1.2/js/dataTables.rowReorder.min.js"></script>
		<script src="<?php echo PATH_TEMPLATE ?>/js/tablas.js"></script>


		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2>Autores</h2>
							<div class="panel-botones">
								<a href="ax-noticias/autores/crear" class="boton success">Nuevo</a>
								<button type="button" id="borraAut" class="boton danger">Borrar</button>
								<div class="alertas hide" id="ajax_alerta"></div>
							</div>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										Listado de autores
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<!-- Para mas info datatables.net -->
									<script>
										$(document).ready(function () {
											var table = $('#tabla-listado').DataTable({
												"language": {
													"sProcessing": "Procesando...",
													"sLengthMenu": "Mostrar _MENU_ registros",
													"sZeroRecords": "No se encontraron resultados",
													"sEmptyTable": "Ningún dato disponible en esta tabla",
													"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
													"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
													"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
													"sInfoPostFix": "",
													"sSearch": "Buscar:",
													"sUrl": "",
													"sInfoThousands": ",",
													"sLoadingRecords": "Cargando...",
													"oPaginate": {
														"sFirst": "Primero",
														"sLast": "Último",
														"sNext": "Siguiente",
														"sPrevious": "Anterior"
													},
													"oAria": {
														"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
														"sSortDescending": ": Activar para ordenar la columna de manera descendente"
													}
												},
												columnDefs: [
													{
														targets: 0,
														visible: false
													}
												]
											});

										});
									</script>
									<div id="result"></div>
									<form method="post" id="formid">
										<table id="tabla-listado" cellspacing="0" width="100%">
											<thead>
												<tr role="row">
													<th>Id</th>
													<th> </th>
													<th>Nombre</th>
													<th>Img</th>
													<th>Link</th>
													<th>Acción</th>
												</tr>
											</thead>
											<tbody>
												<?php if (is_array($autores)): ?>
													<?php foreach($autores as $u):?>
														<tr>
															<td>
																<?= $u['id'] ?>
															</td>
															<td style="width: 57px;"><i class="ax ax-drag-drop"></i>
																<input type="checkbox" name="autores_id[]" value="<?= $u['id'] ?>">
															</td>
															<td>
																<?= $u['nombre'] ?>
															</td>
															<td>
																<?php if($u['imagen'] != ''):?><i class="fa fa-picture-o" aria-hidden="true"><?php endif ?></i></td>
															<td>
																<?= $u['link'] ?>
															</td>
															<td>
																<center><a href="ax-noticias/autores/editar/<?= $u['id'] ?>" class="margin-right-normal"><i class="fa fa-pencil" aria-hidden="true"></i></a>
																	<a href="ax-noticias/autores/borrar/<?= $u['id'] ?>"><i class="fa fa-trash" aria-hidden="true"></i></a></center>
															</td>
														</tr>
														<?php endforeach?>
													<?php endif ?>
											</tbody>
										</table>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->


	<?= $this->insert('html/includes/modules') ?>


	<?= $this->insert('html/includes/footer') ?>


	<script src="<?php echo PATH_TEMPLATE ?>/js/botoneraAut.js"></script>
