		<?= $this->insert('html/includes/header') ?>

		<?= $this->insert('html/includes/barra') ?>

		<?= $this->insert('html/includes/menu') ?>

		<?php require('core/lenguaje/'. LENGUAJE .'/'. LENGUAJE .'.ax-noticias.php'); ?>

		<script src="<?php echo PATH_TEMPLATE ?>/js/tagsinput.js"></script>
		<script src="/a-diario/extras/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
			tinymce.init({
				selector: '#texto',
				theme: "modern",
				height: 400,
				plugins: [
					 "advlist autolink link image lists charmap print preview hr anchor pagebreak",
					 "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
					 "table contextmenu directionality emoticons paste textcolor responsivefilemanager youtube codemirror"
			   ],
				relative_urls: false,
				convert_urls: false,
				browser_spellcheck : true,
				//filemanager_crossdomain: true,
				filemanager_title:"Explorador archivos media",
				external_filemanager_path:"/a-diario/extras/filemanager/",
				external_plugins: { "filemanager" : "plugins/responsivefilemanager/plugin.min.js"},
				codemirror: {
					indentOnInit: true, // Whether or not to indent code on init.
					path: 'CodeMirror'
			   },
			   image_advtab: true,
			   toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
			   toolbar2: "| responsivefilemanager | image | media | link unlink anchor | print preview code | youtube | forecolor backcolor | pagebreak"

			});
		</script>

		<div class="contenido-pagina clearfix" id="contenido-pagina">
			<div class="contenido-pagina-wrapper">
				<div class="contenido-pagina-inner">
					<div id="header-pagina" class="clearfix">
						<div class="header-pagina">
							<h2><?= TITULO_AXNOTICIAS_ARTICULOS ?></h2>
						</div>
					</div>
					<!-- Comienza contenido general del sitio -->
					<div class="row">
						<!-- Columna 01 -->
						<div class="movil-12 pc-12">
							<div class="panel color-bg-info">
								<div class="panel-header">
									<h4 class="panel-title">
										<i class="fa fa-newspaper-o"></i>
										<?= TITULO_AXNOTICIAS_EDITAR_ARTICULO ?><?= htmlspecialchars($ar['art']['titulo']) ?>
									</h4>
									<div class="panel-controls panel-controls-right">
										<span class="collapse-link">
											<i class="fa fa-chevron-up"></i>
										</span>
										<span class="close-link">
											<i class="fa fa-times"></i>
										</span>
									</div>
								</div>
								<div class="panel-body">
									<form action="ax-noticias/articulos/editar/<?= $ar['art']['id']?>" method="post" role="form" enctype="multipart/form-data">
										<div class="botonera">
											<div class="form-grupo">
												<button type="submit" class="boton success"><?= BOTON_ENVIAR ?><i class="fa fa-caret-right"></i></button>
												<a href="ax-noticias/articulos" class="boton danger"><?= BOTON_CANCELAR ?><i class="fa fa-ban"></i></a>
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= CAMPO_FORM_TITULO ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"><i class="fa fa-certificate" aria-hidden="true"></i></span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="titulo" id="titulo" placeholder="<?= CAMPO_FORM_TITULO ?>" required value="<?= htmlspecialchars($ar['art']['titulo']) ?>">
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= CAMPO_FORM_ALIAS ?></label>
											<div class="movil-12 pc-9">
												<input type="text" name="alias" id="alias" placeholder="<?= CAMPO_FORM_ALIAS ?>" value="<?= $ar['art']['alias'] ?>">
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= CAMPO_FORM_CATEGORIA ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"><i class="fa fa-certificate" aria-hidden="true"></i></span></label>
											<div class="movil-12 pc-4">
												<select id="categoria" name="categoria">
													<option value="<?= $ar['art']['categoria'] ?>"><?= $ar['art']['categoria'] ?></option>
													<?php foreach($ca['cat'] as $cate):?>
														<option value="<?= $cate['id'] ?>"><?= $cate['nombre'] ?></option>
													<?php endforeach?>
												</select>
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= CAMPO_FORM_ETIQUETAS ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"><i class="fa fa-certificate" aria-hidden="true"></i></span></label>
											<div class="movil-12 pc-9">
												<input type="text" name="etiquetas" value="<?= $ar['art']['etiquetas'] ?>"  data-role="tagsinput" placeholder="<?= CAMPO_FORM_ETIQUETAS_PLACEHOLDER ?>" />
											</div>
										</div>
										<div class="form-grupo">
											<label class="movil-12 pc-3"><?= CAMPO_FORM_ACTIVAR ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"><i class="fa fa-certificate" aria-hidden="true"></i></span></label>
											<div class="botonSiNo">
												<label class="on">
													<input type="radio" name="publica" value="1" <?php if ($ar['art']['publicar'] == '1'){echo "checked";}?>>
													<span><?= BOTON_SI ?></span>
												</label>
												<label class="off">
													<input type="radio" name="publica" value="0" <?php if ($ar['art']['publicar'] == '0'){echo "checked";}?>>
													<span><?= BOTON_NO ?></span>
												</label>
											</div>
											<label class="movil-12 pc-3 padding-left-grende"><?= CAMPO_FORM_DESTACADO ?><span class="marcador-rojo" title="<?= CAMPO_FORM_OBLIGATORIO ?>"><i class="fa fa-certificate" aria-hidden="true"></i></span></label>
											<div class="botonSiNo">
												<label class="on">
													<input type="radio" name="destacado" value="1" <?php if ($ar['art']['destacado'] == '1'){echo "checked";}?>>
													<span><?= BOTON_SI ?></span>
												</label>
												<label class="off">
													<input type="radio" name="destacado" value="0" <?php if ($ar['art']['destacado'] == '0'){echo "checked";}?>>
													<span><?= BOTON_NO ?></span>
												</label>
											</div>
										</div>
										<div id="ud_tab">
											<input type="radio" name="ud_tabs" id="tab1" checked>
											<label for="tab1"><?= CAMPO_TAB_EDITOR ?></label>

											<input type="radio" name="ud_tabs" id="tab2">
											<label for="tab2"><?= CAMPO_TAB_IMGVIDAUDI ?></label>

											<input type="radio" name="ud_tabs" id="tab3">
											<label for="tab3"><?= CAMPO_TAB_PUBLIYMETA ?></label>

											<div id="ud_tab-content1" class="ud_content">
												<div class="form-grupo display-block">
												<?php
												if ($ar['art']['fulltexto'] == ''){
													$texto = $ar['art']['introtexto'];
												}else{
													$texto = $ar['art']['introtexto'] . "<hr id='system-readmore' />" . $ar['art']['fulltexto'];
												}
												?>
												<textarea name="texto" id="texto"><?= $texto ?></textarea>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_AUTOR ?></label>
													<div class="movil-12 pc-9" >
														<select id="autor" name="autor">
															<option value="<?= $ar['art']['autor'] ?>"><?= $ar['art']['autor'] ?></option>
															<?php foreach($aut['au'] as $autor):?>
																<option value="<?= $autor['nombre'] ?>"><?= $autor['nombre'] ?></option>
															<?php endforeach?>
														</select>
													</div>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_FUENTE ?></label>
													<div class="movil-12 pc-9" >
														<select id="fuente" name="fuente">
															<option value="<?= $ar['art']['fuente'] ?>"><?= $ar['art']['fuente'] ?></option>
															<?php foreach($fuen['fue'] as $fuente):?>
																<option value="<?= $fuente['nombre'] ?>"><?= $fuente['nombre'] ?></option>
															<?php endforeach?>
														</select>
													</div>
												</div>
											</div>

											<div id="ud_tab-content2" class="ud_content">
												<div class="form-grupo">
													<div class="form-grupo movil-12 pc-4 position-relative">
														<label class="movil-12 pc-3"><?= CAMPO_FORM_IMAGEN ?></label>
														<div class="fileinput movil-12 pc-9">
															<input  id="foto" name="foto" type="text" value="<?= $ar['art']['foto'] ?>" class="file-input margin-bottom-normal" placeholder="<?= CAMPO_FORM_IMAGEN_PLACEHOLDER ?>">
															<a href="javascript:open_popup('/a-diario/extras/filemanager/dialog.php?type=0&popup=1&field_id=foto&fldr=fotos&relative_url=images/')" class="boton boton-file info" type="button"><?= BOTON_SELECCIONAR ?></a>
														</div>
														<textarea type="text" name="epigrafe_img" class="movil-12 pc-12 margin-bottom-normal" id="epigrafe_img" placeholder="<?= CAMPO_FORM_EPIGRAFE_IMAGEN_PLACEHOLDER ?>"><?= $ar['art']['epigrafe'] ?></textarea>
														<input type="text" name="fuente_img" class="movil-12 pc-12" id="fuente_img" placeholder="<?= CAMPO_FORM_FUENTE_IMAGEN_PLACEHOLDER ?>" value="<?= $ar['art']['fuente_imagen'] ?>">
													</div>

													<div class="form-grupo movil-12 pc-4 position-relative">
														<label class="movil-12 pc-3"><?= CAMPO_FORM_VIDEO ?></label>
														<div class="fileinput movil-12 pc-9">
															<input  id="video" name="video" type="text" value="<?= $ar['art']['video'] ?>" class="file-input margin-bottom-normal" placeholder="<?= CAMPO_FORM_IMAGEN_PLACEHOLDER ?>">
															<a href="javascript:open_popup('/a-diario/extras/filemanager/dialog.php?type=3&popup=1&field_id=video&fldr=videos')" class="boton boton-file info" type="button"><?= BOTON_SELECCIONAR ?></a>
														</div>
														<textarea type="text" name="epigrafe_vid" class="movil-12 pc-12 margin-bottom-normal" id="epigrafe_vid" placeholder="<?= CAMPO_FORM_EPIGRAFE_VIDEO_PLACEHOLDER ?>"></textarea>
														<input type="text" name="fuente_vid" class="movil-12 pc-12 pc-margen-izquierda-1" id="fuente_vid" placeholder="<?= CAMPO_FORM_FUENTE_VIDEO_PLACEHOLDER ?>" value="<?= $ar['art']['fuente_video'] ?>">
													</div>

													<div class="form-grupo movil-12 pc-4 position-relative">
														<label class="movil-12 pc-3"><?= CAMPO_FORM_AUDIO ?></label>
														<div class="fileinput movil-12 pc-9">
															<input  id="audio" name="audio" type="text" value="<?= $ar['art']['audio'] ?>" class="file-input margin-bottom-normal" placeholder="<?= CAMPO_FORM_IMAGEN_PLACEHOLDER ?>">
															<a href="javascript:open_popup('/a-diario/extras/filemanager/dialog.php?type=2&popup=1&field_id=audio&fldr=audios')" class="boton boton-file info" type="button"><?= BOTON_SELECCIONAR ?></a>
														</div>
														<textarea type="text" name="epigrafe_audi" class="movil-12 pc-12 margin-bottom-normal" id="epigrafe_audi" placeholder="<?= CAMPO_FORM_EPIGRAFE_AUDIO_PLACEHOLDER ?>"></textarea>
														<input type="text" name="fuente_audi" class="movil-12 pc-12 pc-margen-izquierda-1" id="fuente_audi" placeholder="<?= CAMPO_FORM_FUENTE_AUDIO_PLACEHOLDER ?>" value="<?= $ar['art']['fuente_audio'] ?>">
													</div>
												</div>
											</div>

											<div id="ud_tab-content3" class="ud_content">
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_FECHACREACION ?></label>
													<div class="movil-12 pc-9" >
														<input type="text" name="fecha_creado" class="movil-12" id="fecha_creado" value="<?= $ar['art']['fecha_creado'] ?>" disabled>
													</div>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_FECHAMODIFICADO ?></label>
													<div class="movil-12 pc-9" >
														<input type="text" name="fecha_modificado" class="movil-12" id="fecha_modificado" value="<?= $ar['art']['fecha_modificado'] ?>" disabled>
													</div>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_REVISION ?></label>
													<div class="movil-12 pc-9" >
													 <input type="text" name="revision" class="movil-12" id="revision" value="<?= $ar['art']['revision'] ?>" disabled>
													</div>
												</div>

												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_FECHAPUBLICACION ?></label>
													<div class="movil-12 pc-9" >
														<input type="datetime-local" name="fecha_inicio" class="movil-12" id="fecha_inicio" value="<?= $ar['art']['fecha_inicio'] ?>">
													</div>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_FECHAFINALIZACION ?></label>
													<div class="movil-12 pc-9" >
														<input type="datetime-local" name="fecha_fin" class="movil-12" id="fecha_fin" value="<?= $ar['art']['fecha_finaliza'] ?>">
													</div>
												</div>

												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_METADESCRIPCION ?></label>
													<div class="movil-12 pc-9" >
														<textarea type="text" name="metadescrip" class="movil-12" id="metadescrip"><?= $ar['art']['metadescripcion'] ?></textarea>
													</div>
												</div>
												<div class="form-grupo">
													<label class="movil-12 pc-3"><?= CAMPO_FORM_METAPALABRACLAVE ?></label>
													<div class="movil-12 pc-9" >
														<input type="text" name="metapalabra" class="movil-12" id="metapalabra" value="<?= $ar['art']['metapalabraclave'] ?>">
													</div>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- Finaliza contenido general del sitio -->
				</div>
			</div>
		</div>

	</div>
	<!-- FINALIZA EL WRAPPER -->

	<script>
		function open_popup(url){
			var w = 880;
			var h = 570;
			var l = Math.floor((screen.width-w)/2);
			var t = Math.floor((screen.height-h)/2);
			var win = window.open(url, '<?= CAMPO_FORM_EXPLORADORARCHIVOS ?>', "scrollbars=1,width=" + w + ",height=" + h + ",top=" + t + ",left=" + l);
		}
	</script>

	<?= $this->insert('html/includes/modules') ?>


	<?= $this->insert('html/includes/footer') ?>
